@startuml

par 处理其他客户端的服务请求
loop
activate 抽象服务类
抽象服务类 -> 抽象服务类 : 监听服务请求
抽象服务类 -> 抽象服务类 : 处理请求
抽象服务类 -> 抽象服务类 : 返回处理结果
end
else 向服务端请求服务
activate 抽象服务类
loop
抽象服务类 -> 服务发现模块 : 获取服务地址
activate  服务发现模块
return 服务地址
抽象服务类 -> 目标服务端 : 发起服务请求
activate 目标服务端
目标服务端 -> 目标服务端 :处理请求
return 处理结果

end
end

@enduml