activate 通信抽象模块
loop
通信抽象模块 -> 通信抽象模块 : 监听新消息
alt 有新消息
通信抽象模块 -> 订阅者模块 : 调用订阅者模块回调函数
activate 订阅者模块
订阅者模块 -> 订阅者模块 : 将新消息压入消息队列
订阅者模块 -> 调度模块 : 激活调度任务
deactivate 订阅者模块
activate 调度模块
调度模块 -> 任务模块 : 激活任务
deactivate 调度模块
activate 任务模块 
任务模块 -> 任务模块 : 运行
deactivate 任务模块
end
end
