@startuml
actor 用户
用户 -> 发布者模块 : 注册发布者
发布者模块 -> 发布者模块 : 配置文件校验
alt 校验失败
    发布者模块 --> 用户 : 注册失败 
else 校验成功
    activate 发布者模块

    发布者模块 -> 通信抽象模块 : 传送发布者配置文件

    activate 通信抽象模块
    通信抽象模块 -> 抽象发布类 : 创建抽象发布类
    activate 抽象发布类
    抽象发布类 -> 发布管理类 : 创建发布管理类
    activate 发布管理类 
    发布管理类 -> 发布管理类 : 创建进程间通信管理类
    发布管理类 -> 发布管理类 : 创建进程内通信管理类
    发布管理类 -> 发布管理类 : 创建网络通信管理类
    return 创建成功
    抽象发布类 -> 抽象发布类 : 保存发布管理类
    return 创建成功
    ' deactivate 抽象发布类

    通信抽象模块 -> 通信抽象模块 : 创建抽象发布者配置文件
    通信抽象模块 -> 通信抽象模块 : 生成服务发现请求参数
    通信抽象模块 -> 服务发现模块 : 发出注册请求

    activate 服务发现模块
    loop 直到匹配成功
        服务发现模块 -> 服务发现模块 : 根据抽象发布者配置文件\n匹配订阅者
    end
    服务发现模块 -> 服务发现模块 : 执行回调函数
    服务发现模块 --> 通信抽象模块 -- : 注册成功
    通信抽象模块 --> 发布者模块 -- : 注册成功
    ' deactivate 通信抽象模块
    发布者模块 --> 用户: 注册成功
    ' activate 发布管理类

    用户 -> 发布者模块 : 发布消息
    发布者模块 -> 发布者模块 : 序列化数据
    发布者模块 -> 发布者模块 : 将数据转换为抽象数据类型
    发布者模块 -> 通信抽象模块 : 发布消息
    activate 通信抽象模块
    通信抽象模块 -> 通信抽象模块 : 查找抽象发布类
    通信抽象模块 -> 抽象发布类 : 发布消息
    activate 抽象发布类
    抽象发布类 -> 发布管理类 : 发布消息
    activate 发布管理类
    发布管理类 -> 发布管理类 : 根据通信链路发布消息
    return 发布成功
    return 发布成功
    return 发布成功
    发布者模块 --> 用户 -- : 发布成功


end
@enduml