@startuml
left to right direction
skinparam packageStyle rectangle
actor 用户
rectangle 调度策略管理 {
用户 -- (设置基于时间\n的调度策略)
(设置基于时间\n的调度策略) .-> (设置调度频率) : <<包含>>
(设置基于时间\n的调度策略) .-> (设置调度任务) : <<包含>>

}

@enduml
