@startuml

database 中心节点 as z
node 服务发现模块1 as s1
node 服务发现模块2 as s2
node 服务发现模块3 as s3

s1 --> z : 1.注册发布者
z ..> s1 : 2.关联服务发现模块信息 

s1 --> s1 : 3.根据订阅者信息\n选择通信方式

s1 ..> s2 : 4.连接地址\n订阅者信息
s1 ..> s3 : 4.连接地址\n订阅者信息

s2 --> s2 : 连接
s3 --> s3 : 连接
@enduml
