skinparam style strictuml
@startuml
actor 用户
用户 -> 服务服务端 : 创建服务端
activate 服务服务端
服务服务端 -> 通信抽象模块 : 传递服务端配置文件
activate 通信抽象模块
通信抽象模块 -> 抽象服务类 : 传递服务端配置文件
activate 抽象服务类
抽象服务类 -> 抽象服务类 : 绑定服务至RPC服务器
抽象服务类 --> 通信抽象模块 : 绑定成功
loop 
    抽象服务类 -> 抽象服务类 : 监听服务请求
    抽象服务类 -> 抽象服务类 : 处理请求体
    抽象服务类 -> 抽象服务类 : 返回处理结果
end

通信抽象模块 -> 通信抽象模块 : 生成服务发现请求参数
通信抽象模块 -> 服务发现模块 : 发出创建请求
activate 服务发现模块
服务发现模块 -> 服务发现模块 : 保存服务端配置文件
服务发现模块 -> 服务发现模块 : 更新网络拓扑
服务发现模块 --> 通信抽象模块 -- : 创建成功
通信抽象模块 --> 服务服务端 -- : 创建成功
服务服务端 --> 用户 -- : 创建成功




@enduml