@startuml
|InternalSubscriberImpl|
start
:创建订阅者;
if (配置文件参数检查) is (合法) then
:注册订阅者;
else (不合法)
end
endif

|CommunicationAbstract|
:创建抽象订阅类;
:设置服务发现查询参数;
|ServiceDiscoveryManager|
if (查询参数检查) is (合法) then
:更新网络拓扑;
:返回相关发布者信息;
else (不合法)
end
endif

|SubAbstract|
:根据订阅者信息建立通信连接;
stop
@enduml

