skinparam style strictuml
@startuml
actor 用户
用户 -> 订阅者模块 : 删除订阅者
activate 订阅者模块
订阅者模块 -> 调度模块 : 删除调度任务
activate 调度模块
调度模块 -> 调度模块 : 删除调度任务
return 删除成功
订阅者模块 -> 通信抽象模块 : 发出删除请求
activate 通信抽象模块
通信抽象模块 -> 通信抽象模块 : 删除订阅管理类
通信抽象模块 -> 通信抽象模块 : 删除抽象订阅类
通信抽象模块 -> 通信抽象模块 : 生成服务发现请求参数
通信抽象模块 -> 服务发现模块 : 发出删除请求
activate 服务发现模块
服务发现模块 -> 服务发现模块 : 删除订阅者信息
服务发现模块 -> 服务发现模块 : 更新网络拓扑
服务发现模块 -> 服务发现模块 : 执行匹配发布者回调函数\n更新连接
return 删除成功
return 删除成功
return 删除成功

用户 -> 订阅者模块 : 修改进程通信方式
activate 订阅者模块
订阅者模块 -> 订阅者模块 : 修改配置文件
订阅者模块 -> 通信抽象模块 : 传递配置文件
activate 通信抽象模块
通信抽象模块 -> 通信抽象模块 : 生成服务发现请求参数
通信抽象模块 -> 服务发现模块 : 发出修改请求
activate 服务发现模块
服务发现模块 -> 服务发现模块 : 修改订阅者信息
服务发现模块 -> 服务发现模块 : 更新网络拓扑
服务发现模块 -> 服务发现模块 : 执行匹配发布者回调函数\n更新连接
return 修改成功
return 修改成功
return 修改成功
@enduml