@startuml
left to right direction
skinparam packageStyle rectangle
actor 用户
用户 -- (管理话题通信)
用户 -- (管理服务通信)
用户 -- (自适应选择通信方式)
用户 -- (调度策略管理)
用户 -- (序列化中间语言生成)
用户 -- (查询网络拓扑信息)

(管理话题通信) .-> (管理发布者) : <<包含>>
(管理话题通信) .-> (管理订阅者) : <<包含>>
(管理服务通信) .-> (管理服务端) : <<包含>>
(管理服务通信) .-> (管理客户端) : <<包含>>
(调度策略管理) .-> (设置调度任务) : <<包含>>
(调度策略管理) .-> (设置调度频率) : <<包含>>
(查询网络拓扑信息) .-> (查询话题通信信息) : <<包含>>
(查询网络拓扑信息) .-> (查询服务通信信息) : <<包含>>

@enduml


