activate 调度模块
loop
调度模块 -> 调度模块 : 计算调度剩余时间
alt 大于零
调度模块 -> 调度模块 : 睡眠调度剩余时间
调度模块 -> 任务模块 : 激活任务
activate 任务模块
任务模块 -> 任务模块 : 运行
任务模块 --> 调度模块 --: 运行成功
' deactivate 任务模块
else 小于零
调度模块 -> 任务模块 : 激活任务
activate 任务模块
任务模块 -> 任务模块 : 运行
任务模块 --> 调度模块 --: 运行成功
end
end
