@startuml
left to right direction
skinparam packageStyle rectangle
actor 用户

rectangle 管理服务 {
用户 -- (管理服务端)
(管理服务端) .-> (创建服务端) : <<包含>>
(管理服务端) .-> (删除服务端) : <<包含>>
(管理服务端) .-> (修改服务端通信域) : <<包含>>
(修改服务端通信域) .-> (修改为全域) : <<包含>>
(修改服务端通信域) .-> (修改为本机域) : <<包含>>

(创建服务端) .-> (创建本地域服务端) : <<包含>>
(创建服务端) .-> (创建全域服务端) : <<包含>>


用户 -- (管理客户端)
(管理客户端) .-> (创建客户端) : <<包含>>
(管理客户端) .-> (删除客户端) : <<包含>>
(管理客户端) .-> (修改客户端通信域) : <<包含>>
(修改客户端通信域) .-> (修改为全域) : <<包含>>
(修改客户端通信域) .-> (修改为本机域) : <<包含>>
(创建客户端) .-> (创建本地域客户端) : <<包含>>
(创建客户端) .-> (创建全域客户端) : <<包含>>
}
rectangle 查询服务信息 {
用户 -- (查询服务端信息)
(查询服务端信息) .-> (本机域查询) 
(查询服务端信息) .-> (全域查询) 
(本机域查询) ..> (全量查询) 
(全域查询) ..> (全量查询) 
(本机域查询) ..> (按服务名称查询) 
(全域查询) ..> (按服务名称查询)
}
@enduml

