@startuml
left to right direction
skinparam packageStyle rectangle
actor 发布者或订阅者
rectangle 通信模式管理 {
发布者或订阅者 -- (设置通信模式)
(设置通信模式) .-> (共享内存通信) : <<包含>>
(设置通信模式) .-> (网络通信) : <<包含>>
(设置通信模式) .-> (进程内通信) : <<包含>>
发布者或订阅者 -- (修改通信模式)
修改通信模式 .-> (立即修改) : <<包含>>
修改通信模式 .-> (惰性修改) : <<包含>>
}
rectangle 分布式通信系统{
    (共享内存通信) <-. 参数检查 : <<扩展>>
    (网络通信) <-. 参数检查 : <<扩展>>
    (进程内通信) <-. 参数检查 : <<扩展>>
    (立即修改) <-. 参数检查 : <<扩展>>
    (惰性修改) <-. 参数检查 : <<扩展>>

}
@enduml
