@startuml
left to right direction
skinparam packageStyle rectangle
actor 发布者或订阅者
rectangle 查询通信单元信息 {
发布者或订阅者 -- (查询发布者信息)
发布者或订阅者 -- (查询订阅者信息)
(查询发布者信息) .-> (本机域查询) : <<包含>>
(查询发布者信息) .-> (全域查询) : <<包含>>
(查询订阅者信息) .-> (本机域查询) : <<包含>>
(查询订阅者信息) .-> (全域查询) : <<包含>>
(本机域查询) .-> (按话题查询) : <<扩展>>
(全域查询) .-> (按话题查询) : <<扩展>>
(本机域查询) .-> (全量查询) : <<扩展>>
(全域查询) .-> (全量查询) : <<扩展>>
}
' rectangle 分布式通信系统 {
'     (本地域订阅者) <-. (参数检查) : <<扩展>>
'     (局部域订阅者) <-.(参数检查): <<扩展>>
'     (全域订阅者) <-.(参数检查): <<扩展>>
'     (立即删除订阅者) <-.(参数检查): <<扩展>>
'     (惰性删除订阅者) <-.(参数检查) : <<扩展>>
' }
@enduml


