@startuml
left to right direction
skinparam packageStyle rectangle
actor 用户
rectangle 管理通信单元 {
用户 -- (管理发布者单元)
(管理发布者单元) .-> (注册发布者单元) : <<包含>>
(管理发布者单元) .-> (删除发布者单元) : <<包含>>
(管理发布者单元) .-> (修改发布者通信域) : <<包含>>
(修改发布者通信域) .-> (修改为全域) : <<包含>>
(修改发布者通信域) .-> (修改为本机域) : <<包含>>
(注册发布者单元) .-> (本地域发布者) : <<包含>>
(注册发布者单元) .-> (全域发布者) : <<包含>>

用户 -- (管理订阅者单元)
(管理订阅者单元) .-> (注册订阅者单元) : <<包含>>
(管理订阅者单元) .-> (删除订阅者单元) : <<包含>>
(管理订阅者单元) .-> (修改订阅者通信域) : <<包含>>
(修改订阅者通信域) .-> (修改为全域) : <<包含>>
(修改订阅者通信域) .-> (修改为本机域) : <<包含>>
(注册订阅者单元) .-> (本地域订阅者) : <<包含>>
(注册订阅者单元) .-> (全域订阅者) : <<包含>>
删除订阅者单元 .-> (立即删除订阅者) : <<包含>>
删除订阅者单元 .-> (惰性删除订阅者) : <<包含>>
}
rectangle 查询通信单元信息 {
用户 -- (查询发布者信息)
用户 -- (查询订阅者信息)
(查询发布者信息) .-> (本机域查询) : <<包含>>
(查询发布者信息) .-> (全域查询) : <<包含>>
(查询订阅者信息) .-> (本机域查询) : <<包含>>
(查询订阅者信息) .-> (全域查询) : <<包含>>
(本机域查询) .-> (按话题查询) : <<包含>>
(全域查询) .-> (按话题查询) : <<包含>>
(本机域查询) .-> (全量查询) : <<包含>>
(全域查询) .-> (全量查询) : <<包含>>
}
@enduml


