@startuml
left to right direction
skinparam packageStyle rectangle
actor 订阅者
rectangle 注册发布者单元 {
订阅者 -- (注册订阅者单元)
(注册订阅者单元) .-> (本地域订阅者) : <<包含>>
(注册订阅者单元) .-> (局部域订阅者) : <<包含>>
(注册订阅者单元) .-> (全域订阅者) : <<包含>>
订阅者 -- (删除订阅者单元)
删除订阅者单元 .-> (立即删除订阅者) : <<包含>>
删除订阅者单元 .-> (惰性删除订阅者) : <<包含>>
}
rectangle 分布式通信系统 {
    (本地域订阅者) <-. (参数检查) : <<扩展>>
    (局部域订阅者) <-.(参数检查): <<扩展>>
    (全域订阅者) <-.(参数检查): <<扩展>>
    (立即删除订阅者) <-.(参数检查): <<扩展>>
    (惰性删除订阅者) <-.(参数检查) : <<扩展>>
}
@enduml


